import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import { useState, useEffect, useContext } from "react";
import { GlobalContext } from "../provider/GlobalContext";

import styles from "../../styles/Home.module.scss";

export default function Home() {
  const context = useContext(GlobalContext);

  const [appTheme, setAppTheme] = useState();

  let theme = appTheme == "light" ? `${styles["light"]}` : `${styles["dark"]}`;

  useEffect(() => {
    setAppTheme(context.globalTheme);
  }, [context.globalTheme]);

  return (
    <div className={theme}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <main className={styles.main}></main>
      </div>
    </div>
  );
}
